// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

// Shared AGI Jobs v2 constants.
// @dev Auto-generated by scripts/generate-constants.ts
// Canonical $AGIALPHA token on Ethereum mainnet.
address constant AGIALPHA = 0xA61a3B3a130a9c20768EEBF97E21515A6046a1fA;

// Standard decimals for $AGIALPHA.
uint8 constant AGIALPHA_DECIMALS = 18;

// ERC-20 metadata for $AGIALPHA.
string constant AGIALPHA_SYMBOL = "AGIALPHA";
string constant AGIALPHA_NAME = "AGI ALPHA";

// Base unit scaling factor for $AGIALPHA (10 ** decimals).
uint256 constant TOKEN_SCALE = 1000000000000000000;

// Address used for burning tokens.
address constant BURN_ADDRESS = 0x0000000000000000000000000000000000000000;
